version: '3.8'

services:
  web:
    build:
      context: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/users_db
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
